/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 15/11/2012, 08:18:14
 */
package br.ajuda.generico.view;

import br.ajuda.generico.controller.TemaController;
import br.ajuda.generico.entities.Tema;
import br.ajuda.generico.util.AbstractFrame;
import java.awt.Component;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author jacob
 */
public class MainFrame extends AbstractFrame {

    public static final String OBJ_TEMA = "tema";
    public static final String OPER_TEMA = "operacao_tema";
    private TemaController temaController;

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        try {
            temaController = new TemaController();
        } catch (Exception ex) {
            controladorDespacho.registraEexibe(ex);
        }
        adicTemaList.setCellRenderer(new ListCellRenderer() {

            DefaultListCellRenderer renderer = new DefaultListCellRenderer();

            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                if (value instanceof Tema) {
                    Tema t = (Tema) value;
                    return renderer.getListCellRendererComponent(list, t.getTituloTema(), index, isSelected, cellHasFocus);
                } else {
                    return renderer.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                }
            }
        });

        adicTemaList.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                estadoAltExclTema();
                boolean b = e.getValueIsAdjusting();
                System.out.println(b);
            }
        });
    }

    public void estadoAdicTema() {
        adicTemaButton.setEnabled(true);
        altTemaButton.setEnabled(false);
        excTemaButton.setEnabled(false);
        cancelButton.setEnabled(false);
    }

    public void estadoAltExclTema() {
        adicTemaButton.setEnabled(false);
        altTemaButton.setEnabled(true);
        excTemaButton.setEnabled(true);
        cancelButton.setEnabled(true);
    }

    public void estadoExclTema() {
        adicTemaButton.setEnabled(false);
        altTemaButton.setEnabled(false);
        excTemaButton.setEnabled(true);
        cancelButton.setEnabled(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        adicTemaList = new br.com.swing.componentes.personalizados.ui.ListaComFiltro<Tema>();
        listaComFiltro2 = new br.com.swing.componentes.personalizados.ui.ListaComFiltro();
        jPanel4 = new javax.swing.JPanel();
        adicTemaButton = new javax.swing.JButton();
        altTemaButton = new javax.swing.JButton();
        excTemaButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        editorPanel = new javax.swing.JEditorPane();
        jPanel3 = new javax.swing.JPanel();
        editarTButton = new javax.swing.JToggleButton();
        jXStatusBar1 = new org.jdesktop.swingx.JXStatusBar();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        listaComFiltro2.setName("listaComFiltro2"); // NOI18N

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setName("jPanel4"); // NOI18N

        adicTemaButton.setText("AD");
        adicTemaButton.setName("adicTemaButton"); // NOI18N
        adicTemaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicTemaButtonActionPerformed(evt);
            }
        });
        jPanel4.add(adicTemaButton);

        altTemaButton.setText("ALT");
        altTemaButton.setEnabled(false);
        altTemaButton.setName("altTemaButton"); // NOI18N
        altTemaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altTemaButtonActionPerformed(evt);
            }
        });
        jPanel4.add(altTemaButton);

        excTemaButton.setText("EXC");
        excTemaButton.setEnabled(false);
        excTemaButton.setName("excTemaButton"); // NOI18N
        excTemaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excTemaButtonActionPerformed(evt);
            }
        });
        jPanel4.add(excTemaButton);

        cancelButton.setText("CAN");
        cancelButton.setEnabled(false);
        cancelButton.setName("cancelButton"); // NOI18N
        jPanel4.add(cancelButton);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(adicTemaList, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaComFiltro2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adicTemaList, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(listaComFiltro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        editorPanel.setName("editorPanel"); // NOI18N
        jScrollPane1.setViewportView(editorPanel);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        editarTButton.setText("Editar");
        editarTButton.setName("editarTButton"); // NOI18N
        jPanel3.add(editarTButton);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jXStatusBar1.setName("jXStatusBar1"); // NOI18N

        jLabel1.setText("Status:");
        jLabel1.setName("jLabel1"); // NOI18N
        jXStatusBar1.add(jLabel1);

        getContentPane().add(jXStatusBar1, java.awt.BorderLayout.SOUTH);

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText("File");
        jMenu1.setName("jMenu1"); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setName("jMenu2"); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-742)/2, (screenSize.height-516)/2, 742, 516);
    }// </editor-fold>//GEN-END:initComponents

    private void adicTemaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicTemaButtonActionPerformed

        controladorDespacho.despachar(new TemaDialog(this, true));

    }//GEN-LAST:event_adicTemaButtonActionPerformed

    private void altTemaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altTemaButtonActionPerformed
        // TODO impl. alteracao de tema
        controladorDespacho.setParam(OBJ_TEMA, adicTemaList.getList().getSelectedValue());
        controladorDespacho.setParam(OPER_TEMA, 2);//se for alteracao
        controladorDespacho.despachar(new TemaDialog(this, true));
    }//GEN-LAST:event_altTemaButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            adicTemaList.adicionarItens(temaController.consultaLista(new Tema()));
        } catch (Exception ex) {
            controladorDespacho.registraEexibe(ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void excTemaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excTemaButtonActionPerformed
        adicTemaList.removerItem(adicTemaList.getItemSelecionado());
        estadoAdicTema();
    }//GEN-LAST:event_excTemaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicTemaButton;
    private br.com.swing.componentes.personalizados.ui.ListaComFiltro<Tema> adicTemaList;
    private javax.swing.JButton altTemaButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JToggleButton editarTButton;
    private javax.swing.JEditorPane editorPanel;
    private javax.swing.JButton excTemaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private org.jdesktop.swingx.JXStatusBar jXStatusBar1;
    private br.com.swing.componentes.personalizados.ui.ListaComFiltro listaComFiltro2;
    // End of variables declaration//GEN-END:variables
}
